@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.netbeans.org/schema/signatures", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package autogenerated.entities.signatures;
