
package autogenerated.entities.signatures;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Signatures complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Signatures">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iems" type="{http://xml.netbeans.org/schema/signatures}IEMS"/>
 *         &lt;element name="headphones" type="{http://xml.netbeans.org/schema/signatures}Headphones"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "signatures")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Signatures", propOrder = {
    "iems",
    "headphones"
})
public class Signatures {

    @XmlElement(required = true)
    protected IEMS iems;
    @XmlElement(required = true)
    protected Headphones headphones;

    /**
     * Gets the value of the iems property.
     * 
     * @return
     *     possible object is
     *     {@link IEMS }
     *     
     */
    public IEMS getIems() {
        return iems;
    }

    /**
     * Sets the value of the iems property.
     * 
     * @param value
     *     allowed object is
     *     {@link IEMS }
     *     
     */
    public void setIems(IEMS value) {
        this.iems = value;
    }

    /**
     * Gets the value of the headphones property.
     * 
     * @return
     *     possible object is
     *     {@link Headphones }
     *     
     */
    public Headphones getHeadphones() {
        return headphones;
    }

    /**
     * Sets the value of the headphones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Headphones }
     *     
     */
    public void setHeadphones(Headphones value) {
        this.headphones = value;
    }

}
