
package autogenerated.entities.audio46.links.products;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the autogenerated.entities.audio46.links.products package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Links_QNAME = new QName("http://xml.netbeans.org/schema/audio46ProductsLinks", "links");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: autogenerated.entities.audio46.links.products
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Links }
     * 
     */
    public Links createLinks() {
        return new Links();
    }

    /**
     * Create an instance of {@link Headphones }
     * 
     */
    public Headphones createHeadphones() {
        return new Headphones();
    }

    /**
     * Create an instance of {@link Earphones }
     * 
     */
    public Earphones createEarphones() {
        return new Earphones();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Links }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xml.netbeans.org/schema/audio46ProductsLinks", name = "links")
    public JAXBElement<Links> createLinks(Links value) {
        return new JAXBElement<Links>(_Links_QNAME, Links.class, null, value);
    }

}
