@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.netbeans.org/schema/audio46ProductsLinks", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package autogenerated.entities.audio46.links.products;
