
package autogenerated.entities.audio46.products;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Products complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Products">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="earphones" type="{http://xml.netbeans.org/schema/audio46/products}Earphones"/>
 *         &lt;element name="headphones" type="{http://xml.netbeans.org/schema/audio46/products}Headphones"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "products")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Products", propOrder = {
    "earphones",
    "headphones"
})
public class Products {

    @XmlElement(required = true)
    protected Earphones earphones;
    @XmlElement(required = true)
    protected Headphones headphones;

    /**
     * Gets the value of the earphones property.
     * 
     * @return
     *     possible object is
     *     {@link Earphones }
     *     
     */
    public Earphones getEarphones() {
        return earphones;
    }

    /**
     * Sets the value of the earphones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Earphones }
     *     
     */
    public void setEarphones(Earphones value) {
        this.earphones = value;
    }

    /**
     * Gets the value of the headphones property.
     * 
     * @return
     *     possible object is
     *     {@link Headphones }
     *     
     */
    public Headphones getHeadphones() {
        return headphones;
    }

    /**
     * Sets the value of the headphones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Headphones }
     *     
     */
    public void setHeadphones(Headphones value) {
        this.headphones = value;
    }

}
